import type { Building, Unit } from '../types/game';

export const INITIAL_RESOURCES = {
  wood: 500,
  clay: 500,
  iron: 500,
  food: 500,
};

export const BUILDINGS: Record<string, Building> = {
  headquarters: {
    id: 'headquarters',
    name: 'Headquarters',
    level: 1,
    woodCost: 90,
    clayCost: 80,
    ironCost: 70,
    buildTime: 180,
    upgrading: false,
    description: 'The headquarters coordinates your village',
    effect: 'Unlocks new buildings',
  },
  barracks: {
    id: 'barracks',
    name: 'Barracks',
    level: 1,
    woodCost: 200,
    clayCost: 170,
    ironCost: 90,
    buildTime: 240,
    upgrading: false,
    description: 'Train units for battle',
    effect: 'Unlocks unit training',
  },
  sawmill: {
    id: 'sawmill',
    name: 'Sawmill',
    level: 1,
    woodCost: 100,
    clayCost: 80,
    ironCost: 80,
    buildTime: 150,
    upgrading: false,
    description: 'Produces wood',
    effect: '+5 wood per minute per level',
  },
  claypit: {
    id: 'claypit',
    name: 'Clay Pit',
    level: 1,
    woodCost: 80,
    clayCost: 100,
    ironCost: 80,
    buildTime: 150,
    upgrading: false,
    description: 'Produces clay',
    effect: '+5 clay per minute per level',
  },
  ironmine: {
    id: 'ironmine',
    name: 'Iron Mine',
    level: 1,
    woodCost: 100,
    clayCost: 80,
    ironCost: 90,
    buildTime: 180,
    upgrading: false,
    description: 'Produces iron',
    effect: '+5 iron per minute per level',
  },
  farm: {
    id: 'farm',
    name: 'Farm',
    level: 1,
    woodCost: 80,
    clayCost: 100,
    ironCost: 70,
    buildTime: 150,
    upgrading: false,
    description: 'Produces food',
    effect: '+5 food per minute per level',
  },
  warehouse: {
    id: 'warehouse',
    name: 'Warehouse',
    level: 1,
    woodCost: 130,
    clayCost: 160,
    ironCost: 90,
    buildTime: 180,
    upgrading: false,
    description: 'Stores resources',
    effect: 'Increases resource storage capacity',
  },
  wall: {
    id: 'wall',
    name: 'Wall',
    level: 0,
    woodCost: 50,
    clayCost: 100,
    ironCost: 20,
    buildTime: 120,
    upgrading: false,
    description: 'Defends your village',
    effect: 'Increases defense bonus',
  },
};

export const UNITS: Record<string, Unit> = {
  spearman: {
    id: 'spearman',
    name: 'Spearman',
    woodCost: 50,
    clayCost: 30,
    ironCost: 10,
    foodCost: 1,
    trainTime: 30,
    attack: 10,
    defense: 15,
    description: 'Basic infantry unit with spear',
  },
  swordsman: {
    id: 'swordsman',
    name: 'Swordsman',
    woodCost: 30,
    clayCost: 30,
    ironCost: 70,
    foodCost: 1,
    trainTime: 45,
    attack: 25,
    defense: 50,
    description: 'Strong defensive infantry',
  },
  axeman: {
    id: 'axeman',
    name: 'Axeman',
    woodCost: 60,
    clayCost: 30,
    ironCost: 40,
    foodCost: 1,
    trainTime: 40,
    attack: 40,
    defense: 10,
    description: 'Offensive infantry unit',
  },
  archer: {
    id: 'archer',
    name: 'Archer',
    woodCost: 100,
    clayCost: 30,
    ironCost: 60,
    foodCost: 1,
    trainTime: 50,
    attack: 15,
    defense: 50,
    description: 'Ranged unit with bow',
  },
  cavalry: {
    id: 'cavalry',
    name: 'Light Cavalry',
    woodCost: 125,
    clayCost: 100,
    ironCost: 250,
    foodCost: 4,
    trainTime: 90,
    attack: 130,
    defense: 30,
    description: 'Fast mounted unit',
  },
};

export const PRODUCTION_RATE = 5; // resources per minute per building level
export const PRODUCTION_INTERVAL = 60000; // 1 minute in milliseconds
